version: '3.7'

services:
  fast_api:
    build: ./
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"



